[config]
reload_apps = false

[templates.quickshell_repo]
input_path = '~/.config/matugen/templates/quickshell/Matugen.qml'
output_path = '~/dotfiles/.config/quickshell/theme/Matugen.qml'

[templates.quickshell_live]
input_path = '~/.config/matugen/templates/quickshell/Matugen.qml'
output_path = '~/.config/quickshell/theme/Matugen.qml'

[templates.quickshell_json_repo]
input_path = '~/.config/matugen/templates/quickshell/Matugen.json'
output_path = '~/dotfiles/.config/quickshell/theme/Matugen.json'

[templates.quickshell_json_live]
input_path = '~/.config/matugen/templates/quickshell/Matugen.json'
output_path = '~/.config/quickshell/theme/Matugen.json'

[templates.quickshell_colors]
input_path = '~/.config/matugen/templates/quickshell/colors.json'
output_path = '~/.local/state/quickshell/generated/colors.json'
