#!/usr/bin/env bash

# Get default sink
DEFAULT_SINK=$(pactl info | grep "Default Sink" | awk '{print $3}')

# Check if Bluetooth sink
if [[ "$DEFAULT_SINK" == *"bluez"* ]]; then
  dev=$(upower -e | grep headset)
  BATTERY=$(upower -i "$dev" | awk -F': +' '/percentage/ {print $2}')
  BATTERY=${BATTERY%\%}

  # Battery icon mapping
  if ((BATTERY <= 20)); then
    BAT_ICON=""
  elif ((BATTERY <= 40)); then
    BAT_ICON=""
  elif ((BATTERY <= 60)); then
    BAT_ICON=""
  elif ((BATTERY <= 80)); then
    BAT_ICON=""
  else
    BAT_ICON=""
  fi

  # Bar output
  ICON=" $BAT_ICON $BATTERY%"
  TOOLTIP="$DEVICE_NAME: $BATTERY%"
  echo "$ICON"
  echo "$TOOLTIP"
fi
