preload = /home/nabin/wallpaper/Dynamic-Wallpapers/Light/Mountain_light.png
wallpaper = eDP-2,/home/nabin/wallpaper/Dynamic-Wallpapers/Light/Mountain_light.png
wallpaper = HDMI-A-1,/home/nabin/wallpaper/Dynamic-Wallpapers/Light/Mountain_light.png
splash = false
