general {
    lock_cmd = /home/nabin/dotfiles/.config/quickshell/scripts/lock-session.sh
    before_sleep_cmd = /home/nabin/dotfiles/.config/quickshell/scripts/lock-session.sh
    after_sleep_cmd = hyprctl dispatch dpms on        # Wake screen after suspend
}

# Screenlock
listener {
    timeout = 120
    on-timeout = /home/nabin/dotfiles/.config/quickshell/scripts/lock-session.sh
}

# DPMS (screen off)
listener {
    timeout = 220
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen on when activity is detected
}

# Suspend
listener {
    timeout = 740
    on-timeout = systemctl suspend
}
