general {
    lock_cmd = ./scripts/check-fullscreen             # Only lock if not fullscreen video
    before_sleep_cmd = loginctl lock-session          # Lock session before sleep
    after_sleep_cmd = hyprctl dispatch dpms on        # Wake screen after suspend
}

# Screenlock
listener {
    timeout = 120
    on-timeout = ./scripts/check-fullscreen && loginctl lock-session
}

# DPMS (screen off)
listener {
    timeout = 140
    on-timeout = ./scripts/check-fullscreen && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend
listener {
    timeout = 740
    on-timeout = ./scripts/check-fullscreen && systemctl suspend
}
