exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = ~/.config/hypr/scripts/apply-gtk-theme.sh

exec-once = hyprctl setcursor  material_cursors 32
exec-once =  kdeconnectd

# Start Polkit
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load Dunst Notification Manager
exec-once = easyeffects --gapplication-service

# Restore wallpaper from the cached selection and sync hyprpaper.conf
exec-once = ~/.config/hypr/scripts/restore-wallpaper.sh
exec-once = [workspace 1 silent] ghostty
exec-once = [workspace 2 silent] zen-browser-bin
exec-once = kanata -c /home/nabin/.config/kanata/config.kbd

# Load cliphist history
exec-once = wl-paste --watch ~/.config/hypr/scripts/store-clipboard.sh
exec-once = quickshell -p ~/dotfiles/.config/quickshell/
