monitor=,2560x1600@165,auto,1.067
monitor=HDMI-A-1 ,1920x1080@200,auto,1

general {
    gaps_in = 1
    gaps_out = 1
    border_size = 1
    col.inactive_border = rgba(4B463966)
    layout = dwindle
    resize_on_border = true
    col.active_border = rgba(DEC56EFF)
}

cursor {
 no_hardware_cursors = true
}

input {
  kb_layout = us
  kb_variant =
  kb_model =
  kb_options =
  numlock_by_default = false
  follow_mouse = 1
  mouse_refocus=false
  touchpad {
      natural_scroll = false
      scroll_factor = 1.0  # Touchpad scroll factor
      middle_button_emulation = true
      clickfinger_behavior = true
  }
  sensitivity = 0 # Pointer speed: -1.0 - 1.0, 0 means no modification.
}


decoration {
  rounding = 5
  blur {
      enabled = true
      size = 8
      passes = 3
      new_optimizations = on
      ignore_opacity = false
      xray = false
  }
  active_opacity = 1.0
  inactive_opacity = 0.96
  fullscreen_opacity = 1.0
}

animations {
  enabled = true
  bezier = wind, 0.16, 1, 0.3, 1
  bezier = winIn, 0.16, 1, 0.3, 1
  bezier = winOut, 0.4, 0, 1, 1
  bezier = liner, 1, 1, 1, 1
  animation = windows, 1, 5, wind, slide
  animation = windowsIn, 1, 5, winIn, slide
  animation = windowsOut, 1, 4, winOut, slide
  animation = windowsMove, 1, 5, wind, slide
  animation = border, 1, 1, liner
  animation = borderangle, 1, 30, liner, once
  animation = fade, 1, 6, default
  animation = workspaces, 1, 5, wind, slide
}

# dwindle {
#     pseudotile = true
#     preserve_split = true
# }

gestures {
  gesture = 3, horizontal, workspace
  gesture = 3, down, mod: ALT, close
  gesture = 3, up, mod: SHIFT, float
  gesture = 3, left, mod: SHIFT, resize
  gesture = 3, up, mod: SUPER, scale: 1.5, fullscreen
  workspace_swipe_invert = true
  workspace_swipe_min_speed_to_force = 30
  workspace_swipe_cancel_ratio = 0.5
  workspace_swipe_create_new = true 
  workspace_swipe_forever = true
}

binds {
  workspace_back_and_forth = false
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}
