windowrule = match:title ^(Picture-in-Picture)$, float on, pin on, move 69.5% 4%

windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(Wifi-tauri)$, float on
windowrule = match:class ^(com.example.wayfi)$, float on

windowrule {
    name = Float nmtui kitty
    match:class = ^(kitty)$
    match:title = ^(nmtui)$
    size = 1000 1000

    float = on
    center = on
    animation = popin
}
windowrule {
    name = Float btop kitty
    match:class = ^(kitty)$
    match:title = ^(btop)$
    size = 1000 1000

    float = on
    center = on
    animation = popin
}

windowrule {
    name = Float pavucontrol
    match:class = (.*org.pulseaudio.pavucontrol.*)
    size = 1000 1000

    float = on
    center = on
    animation = popin
}

windowrule {
    name = Float blueman-manager
    match:class = ^(blueman-manager)$
    size = 1000 1000

    float = on
    center = on
    animation = popin
}


