windowrule = match:title ^(Picture-in-Picture)$, float on, pin on, move 69.5% 4%

windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(Wifi-tauri)$, float on
windowrule = match:class ^(com.example.wayfi)$, float on

windowrule {
    name = Float nmtui kitty
    match:class = ^(kitty)$
    match:title = ^(nmtui)$
    size = 1000 1000

    float = on
    center = on
    animation = popin
}
windowrule {
    name = Float btop kitty
    match:class = ^(kitty)$
    match:title = ^(btop)$
    size = 1000 1000

    float = on
    center = on
    animation = popin
}

windowrule {
    name = Float pavucontrol
    match:class = (.*org.pulseaudio.pavucontrol.*)
    size = 1000 1000

    float = on
    center = on
    animation = popin
}

windowrule {
    name = Float blueman-manager
    match:class = ^(blueman-manager)$
    size = 1000 1000

    float = on
    center = on
    animation = popin
}

windowrule {
    name = Float settings
    match:title = ^(System Settings)
    size = 1000 1000

    float = on
    center = on
    animation = popin
}

windowrule {
    name = Control Center
    match:title = ^(quickshell-controlcenter)$
    move = onscreen 100%-w-20 50%

    float = on
    pin = on
}

windowrule {
    name = Quickshell Bar
    match:title = ^(quickshell-bar)$

    float = off
}


windowrule { 
  name = Transmission
  match:class = ^(com.transmissionbt.transmission_49_12356179)$

  float = on
  size = 1000 1000 
  center = true 
  animation = popin
  }
